import { createFlow } from '@builderbot/bot';
import { flowPrincipal } from './flowPrincipal';
import  flowMenu  from './flowMenu';
import { flowLlamarMenu } from './flowLlamarMenu';
import { flowAyuda } from './flowAyuda';
import flowLicencias from './flowLicencias';
import  flowTramites  from './flowTramites';
import { flowCIC } from './flowCic';
import { flowAdultosmayores } from './flowAdultosmayores';
import { flowCeresito } from './flowCeresito';
import { flowDengue } from './flowDengue';
import  flowEducacion from './flowEducacion';
import { flowHistoria } from './flowHistoria';
import { flowResiduos } from './flowResiduos';
import { flowTurismo } from './flowTurismo';
import { flowActividadesAdultos } from './flowActividadesAdultos';
import { flowAgente } from './flowAgente';
import { flowConsejoAdultos } from './flowConsejoAdultos';
import { flowMujerSegura } from './flowMujerSegura';
import { flowNumeroGuardialocal } from './flowNumeroGuardialocal';
import { flowSeccionesPatio } from './flowSeccionesPatio';
import { flowInactividad } from 'src/utils/idle';
import { flowGenero } from './flowGenero';
import { flowPrimeraVez } from './flowPrimeraVez';
import { flowConsultar } from './reclamo/flowConsultar';
import { flowCrearReclamo } from './crearReclamo';
import {voiceNoteFlow, mediaFlow} from './flowAudios';
import { flowReclamos } from './reclamo/flowReclamos';
import { flowCargarReclamo } from './reclamo/flowCargarReclamo';
import { flowCertificado } from './flowCertificado';
import { flowSalud } from './flowSalud';
import { flowCPC } from './flowCPC';
import { flowCaps } from './flowCaps';
import { flowCongresoMujeres } from './flowCongresoMujeres';
import { flowPoda } from './flowPoda';
import { flowInscripcionPoda } from './flowInscripcionPoda';
export const flow =  createFlow([flowPoda, flowInscripcionPoda, flowCongresoMujeres, flowSalud, flowCaps, flowCPC, flowCertificado, flowCargarReclamo, flowReclamos, flowPrincipal, voiceNoteFlow, mediaFlow, flowMenu, flowLlamarMenu, flowAyuda, flowLicencias, flowTramites, flowCIC, flowAdultosmayores, flowCeresito, flowDengue, flowEducacion, flowHistoria, flowResiduos, flowTurismo, flowActividadesAdultos, flowAgente, flowConsejoAdultos, flowMujerSegura, flowNumeroGuardialocal, flowSeccionesPatio, flowInactividad, flowGenero, flowPrimeraVez, flowConsultar, flowCrearReclamo])